---
- name: Install required dependencies
  apt:
    name: 
      - ca-certificates
    state: present
    update_cache: yes

- name: Create directory for Docker keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository
  copy:
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable\n"
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'

- name: Update package list and install Docker
  apt:
    update_cache: yes
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Adding the Jenkins user to the Docker group
  user:
    name: jenkins
    groups: docker
    append: yes
